---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: echoapp-dev
  namespace: dev
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:dev-*
spec:
  releaseName: echo
  chart:
    git: git@github.com:Roy-Z-DevOps/helm-operator-get-started
    path: charts/echoChart
    ref: master
  values:
    image:
      repository: gcr.io/echoapp-320414/echoapp
      version: v4
    replicaCount: 1
 
