---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: echoapp-dev
  namespace: dev
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:dev-*
spec:
  releaseName: echo
  chart:
    git: git@github.com:Roy-Z-DevOps/helm-operator-get-started
    path: charts/echoChart
    ref: master
  values:
    app:
      container:
        repository: "gcr.io/echoapp-320414/echoapp"
        tag: "dev-1.0.0"
    clusterIssuer:
      namespace: dev
    certificate:
      namespace: dev
    ingress:
      namespace: dev
 
