apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.mongoSecret.name }}
type: Opaque
data:
  MONGODBURL: {{- printf "mongodb://root:%s@echo-mongodb-0.echo-mongodb-headless.%s.svc.cluster.local,echo-mongodb-1.echo-mongodb-headless.%s.svc.cluster.local:27017/echo?authSource=admin" .Values.mongodb.auth.rootPassword .Release.Namespace .Release.Namespace  | b64enc | quote | indent 2 }}
