apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.app.labels.app }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.app.container.port }}