app:
  name: echoappv4-deploy
  labels:
    app: echoapp
    version: v4
  replicaCount: 2
  container:
    name: echoappv4
    image: gcr.io/echoapp-320414/echoapp
    tag: latest
    port: 3000
  requests:
    memory: "64Mi"
    cpu: "250m"
  limits:
    memory: "128Mi"
    cpu: "450m"

mongoSecret:
  name: mongodb-secret
  #url: bW9uZ29kYjovL3Jvb3Q6cGFzc3dvcmRAZWNoby1tb25nb2RiLTAuZWNoby1tb25nb2RiLWhlYWRsZXNzLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWwsZWNoby1tb25nb2RiLTEuZWNoby1tb25nb2RiLWhlYWRsZXNzLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWw6MjcwMTcvZWNobz9hdXRoU291cmNlPWFkbWluCg==


config: 
  name: echov4config
  port: "\"3000\""
  loglevel: "info"
  persist: "\"true\""
  dbname: "echo"
  
service:
  name: echoservice
  port: 80
  
clusterIssuer:
  name: letsencrypt
  namespace: default
  email: rz451997@gmail.com
  server: 'https://acme-v02.api.letsencrypt.org/directory'
  keyname: echo-issuer-account-key
  
certificate:
  name: echo-certificate
  namespace: default
  secretName: echo-certificate-key
  



ingress:
  name: echo-ingress
  namespace: default
  host: k8s-task3-roy.tk

mongodb:
  auth:
    rootPassword: password
  architecture: "replicaset"
