app:
  name: echoappv4-deploy
  labels:
    app: echoapp
    version: v4
  replicaCount: 3
  container:
    name: echoappv4
    image: gcr.io/echoapp-320414/echoappv2 
    port: 3000
  requests:
    memory: "64Mi"
    cpu: "250m"
  limits:
    memory: "128Mi"
    cpu: "450m"

mongoSecret:
  name: mongodb-secret
  url: bW9uZ29kYjovL3Jvb3Q6cGFzc3dvcmRAbW9uZ28tbW9uZ29kYi5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsOjI3MDE3L2VjaG8/YXV0aFNvdXJjZT1hZG1pbgo=

  
config: 
  name: echov4config
  port: "\"3000\""
  loglevel: "info"
  persist: "\"true\""
  dbname: "echo"
  
service:
  name: echoservice
  port: 80
  
clusterIssuer:
  name: letsencrypt
  namespace: cert-manager
  email: rz451997@gmail.com
  server: 'https://acme-v02.api.letsencrypt.org/directory'
  keyname: echo-issuer-account-key
  
ingress:
  name: echo-ingress
#  namespace: default
  host: k8s-task3-roy.tk